import TopBarAndDrawerLayoutContext from "@/components/layoutcontexts/TopBarAndDrawerLayoutContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "nextjs googlemaps",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TopBarAndDrawerLayoutContext>{children}</TopBarAndDrawerLayoutContext>
            </body>
        </html>
    );
}
